// Copies the recipe corpus (repo/data/recipes/*.md) into frontend/content/recipes
// so the app can read it self-contained at build time (works on Vercel regardless of
// the configured root directory). Runs automatically via predev / prebuild.
import { readdirSync, mkdirSync, copyFileSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const dataDir = join(here, "..", "..", "data"); // repo/data
const src = join(dataDir, "recipes"); // repo/data/recipes
const contentDir = join(here, "..", "content"); // frontend/content
const dest = join(contentDir, "recipes"); // frontend/content/recipes
const SKIP = new Set(["TEMPLATE.md", "README.md"]);

mkdirSync(dest, { recursive: true });
let n = 0;
for (const f of readdirSync(src)) {
  if (!f.endsWith(".md") || SKIP.has(f)) continue;
  copyFileSync(join(src, f), join(dest, f));
  n++;
}
console.log(`[sync-recipes] copied ${n} recipes -> content/recipes`);

// Precomputed Coach Mode step questions (generated by gen-step-questions.mjs).
const questionsSrc = join(dataDir, "step-questions.json");
if (existsSync(questionsSrc)) {
  copyFileSync(questionsSrc, join(contentDir, "step-questions.json"));
  console.log("[sync-recipes] copied step-questions.json -> content");
}
