"""Recipe catalog loader for the planning/recommendation lane.

Reads the committed catalog.json (generated by build_catalog.py) so the planner can
reason over the whole library without touching data/recipes at runtime.
"""

from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path

_CATALOG_PATH = Path(__file__).parent / "catalog.json"


@lru_cache(maxsize=1)
def get_catalog() -> list[dict]:
    if not _CATALOG_PATH.exists():
        return []
    return json.loads(_CATALOG_PATH.read_text())


def catalog_summary() -> str:
    """Compact, LLM-friendly text block describing the whole library."""
    lines = []
    for r in get_catalog():
        t = r.get("est_time_min")
        time = f"~{t} min" if t else "time n/a"
        ingredients = ", ".join(r.get("ingredients", [])[:8])
        lines.append(
            f"- id={r['id']} | {r['title']} | {r['category']['label']} | "
            f"{r.get('difficulty', '?')} | {time} | ingredients: {ingredients} | {r.get('description', '')}"
        )
    return "\n".join(lines)
